version: '3.8'

services:
  php-apache:
    build: .
    container_name: php_library_system
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - library_network

  mysql:
    image: mysql:5.7
    container_name: mysql_library
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library_network

networks:
  library_network:
    driver: bridge

volumes:
  mysql_data:
